# TravisCI configuration for szepeviktor/SentencePress

if: "branch = master"

language: "php"
arch:
  - "amd64"
  - "arm64-graviton2"
os:
  - "linux"
dist: "bionic"

php:
  - "7.4"
  - "8.0"

env:
  - TYPOS_VERSION="1.29.4"

jobs:
  include:
    -
      name: "List outdated dependencies"
      arch: "arm64-graviton2"
      php: "7.4"
      script: "composer outdated --no-interaction --direct"
    -
      name: "Search for misspellings"
      before_install: "skip"
      install:
      - |
          mkdir -p "${HOME}/typos"
          wget --progress=dot:mega --directory-prefix="${HOME}/typos" \
              "https://github.com/crate-ci/typos/releases/download/v${TYPOS_VERSION}/typos-v${TYPOS_VERSION}-x86_64-unknown-linux-musl.tar.gz"
          tar -xzvf "${HOME}/typos/typos-v${TYPOS_VERSION}-x86_64-unknown-linux-musl.tar.gz" -C "${HOME}/typos" ./typos
      script:
      - |
          "${HOME}/typos/typos"
cache:
  directories:
    - "${HOME}/.composer/cache"

before_install:
  - "phpenv config-rm xdebug.ini"
  - "composer validate --no-interaction --strict"

install:
  - "composer update --no-interaction"

script:
  - "composer run-script --no-interaction test"
