# TravisCI configuration for szepeviktor/SentencePress

if: "branch = master"

language: "php"
arch:
  - "amd64"
  - "arm64-graviton2"
os:
  - "linux"
dist: "bionic"

php:
  - "7.4"
  - "8.0"

jobs:
  include:
    -
      name: "List outdated dependencies"
      arch: "arm64-graviton2"
      php: "7.4"
      script: "composer outdated --no-interaction --direct"
    -
      name: "Spell check"
      language: "python"
      arch: "arm64-graviton2"
      python: "3.9"
      cache: "pip"
      before_install: "skip"
      install: |
        pip install 'codespell>=2.2'
      script: |
        codespell

cache:
  directories:
    - "${HOME}/.composer/cache"

before_install:
  - "phpenv config-rm xdebug.ini"
  - "composer validate --no-interaction --strict"

install:
  - "composer update --no-interaction"

script:
  - "composer run-script --no-interaction test"
